apiVersion: v2
name: rtdmsdecrypter
description: Micro-service designed to decrypt and split aggregate and transaction files.
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"