microservice-chart:
  namespace: "rtd"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 5
    failureThreshold: 6
    periodSeconds: 5

  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 5
    failureThreshold: 6
    periodSeconds: 5

  podAnnotations: { }

  service:
    create: false

  ingress:
    create: false

  serviceAccount:
    name: "rtd-workload-identity" # Replace with your service account name if using workload identity
    # If using Azure Workload Identity, also add the azure section:
    azure:
      workloadIdentityClientId: "CHANGEME" # Insert your clientId here if needed

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - all
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534

  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-connection-string
    KAFKA_SASL_JAAS_CONFIG_CONSUMER_BLOB_STORAGE_EVENTS: evh-rtd-platform-events-rtd-platform-events-sub-rtd
    INTERNAL_SERVICES_API_KEY: rtd-internal-api-product-subscription-key
    CSV_TRANSACTION_PRIVATE_KEY: cstarblobstorage-private-key
    CSV_TRANSACTION_PRIVATE_KEY_PASS: cstarblobstorage-private-key-passphrase

  tmpVolumeMount:
    create: true
    mounts:
      - name: tmp
        mountPath: /tmp
      - name: logs
        mountPath: /app/logs

  externalConfigMapValues:
    rtddecrypter:
      OPENTELEMETRY_LOG_LEVEL: APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL
      CSV_TRANSACTION_DECRYPT_HOST: CSV_TRANSACTION_DECRYPT_HOST
      AGGREGATES_SPLITTER_LINE_THRESHOLD: AGGREGATES_SPLITTER_LINE_THRESHOLD
      CONTRACTS_SPLITTER_LINE_THRESHOLD: CONTRACTS_SPLITTER_LINE_THRESHOLD
      ENABLE_CHUNK_UPLOAD: ENABLE_CHUNK_UPLOAD
      CONSUMER_TIMEOUT_MS: CONSUMER_TIMEOUT_MS

    rtd-blob-storage-events:
      KAFKA_TOPIC_BLOB_STORAGE_EVENTS: KAFKA_TOPIC_BLOB_STORAGE_EVENTS
      KAFKA_BROKER: KAFKA_BROKER_RTD




